owner: alexmisk
repo: status.zzr.ru

sites:
  - name: zzr.ru
    url: https://zzr.ru
  - name: Control TCP ping
    url: 1.1.1.1

status-website:
  cname: status.zzr.ru
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AHJR status page
