owner: AHRJ
repo: status.zzr.ru

sites:
  - name: zzr.ru
    url: https://zzr.ru
  - name: Control TCP ping
    url: 1.1.1.1

status-website:
  cname: status.zzr.ru
  logoUrl: https://cdn.zzr.ru/static/icons/logo.png
  name: AHJR status page
